_wandb:
    value:
        cli_version: 0.22.3
        e:
            z1x216j9yeej00evlfnemzknp73thdei:
                codePath: Project1.ipynb
                codePathLocal: Project1.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510567378944"
                        used: "427517345792"
                email: xkmetk@stuba.sk
                executable: C:\Users\krist\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: b321a31a2b60e4058bf69bee60149e71d35b7bfd
                    remote: https://github.com/Daweed12/ZNEUS_ZS_Vach_Kmet_Duchon.git
                host: Kristof
                memory:
                    total: "25559359488"
                os: Windows-11-10.0.26200-SP0
                program: Project1.ipynb
                python: CPython 3.13.7
                root: C:\Data\VS\5.Semester\ZNEUS\projekt\ZNEUS_ZS_Vach_Kmet_Duchon
                startedAt: "2025-11-10T08:44:16.585210Z"
                writerId: z1x216j9yeej00evlfnemzknp73thdei
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.13.7
            "5": 0.22.3
            "8":
                - 1
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 512
lr:
    value: 0.001
max_epochs:
    value: 80
module__dropout_rate:
    value: 0.2
module__hidden_layers:
    value:
        - 256
        - 128
name:
    value: Test_5_F1_0.576
optimizer:
    value: torch.optim.adam.Adam
