_wandb:
    value:
        cli_version: 0.22.0
        e:
            ei8w2t3f3njryemeyhj0qf1df6g2335h:
                codePath: Project1.ipynb
                codePathLocal: Project1.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1022632464384"
                        used: "590942846976"
                email: xvachd@stuba.sk
                executable: C:\Users\david\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
                git:
                    commit: de5b8ecf21c362b0ad55aca54036839ce7d94fa1
                    remote: https://github.com/Daweed12/ZNEUS_ZS_Vach_Kmet_Duchon.git
                host: razdvach
                memory:
                    total: "33805824000"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\david\zneus\zneus_2025\ZNEUS_ZS_Vach_Kmet_Duchon\Project1.ipynb
                python: CPython 3.11.9
                root: c:\Users\david\zneus\zneus_2025\ZNEUS_ZS_Vach_Kmet_Duchon
                startedAt: "2025-11-10T16:30:09.533336Z"
                writerId: ei8w2t3f3njryemeyhj0qf1df6g2335h
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 32
                - 53
            "2":
                - 1
                - 5
                - 32
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.11.9
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
batch_size:
    value: 512
lr:
    value: 0.0006
max_epochs:
    value: 60
module__dropout_rate:
    value: 0.3
module__hidden_layers:
    value:
        - 640
        - 320
        - 160
name:
    value: Test_26_F1_0.573
optimizer:
    value: torch.optim.adam.Adam
