_wandb:
    value:
        cli_version: 0.22.3
        e:
            j78axkgk3py4tfqlx80671rllrxdn2fg:
                codePath: Project1.ipynb
                codePathLocal: Project1.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510567378944"
                        used: "427284471808"
                email: xkmetk@stuba.sk
                executable: C:\Users\krist\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 60541f28e9414896bd969cafa21769f64ca82f22
                    remote: https://github.com/Daweed12/ZNEUS_ZS_Vach_Kmet_Duchon.git
                host: Kristof
                memory:
                    total: "25559359488"
                os: Windows-11-10.0.26200-SP0
                program: Project1.ipynb
                python: CPython 3.13.7
                root: C:\Data\VS\5.Semester\ZNEUS\projekt\ZNEUS_ZS_Vach_Kmet_Duchon
                startedAt: "2025-11-09T18:06:19.757Z"
                writerId: j78axkgk3py4tfqlx80671rllrxdn2fg
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.13.7
            "5": 0.22.3
            "8":
                - 1
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 1024
lr:
    value: 0.0008
max_epochs:
    value: 60
module__dropout_rate:
    value: 0.3
module__hidden_layers:
    value:
        - 512
        - 256
        - 128
name:
    value: Test_1_F1_0.570
optimizer:
    value: torch.optim.adam.Adam
