_wandb:
    value:
        cli_version: 0.22.3
        e:
            agc3dc6u8ff91xiqoalef0q4lws08amr:
                codePath: Project1.ipynb
                codePathLocal: Project1.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510567378944"
                        used: "424518893568"
                email: xkmetk@stuba.sk
                executable: C:\Users\krist\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: ca5ed1e2b02c28bde5ee8d683fd554784fabc01c
                    remote: https://github.com/Daweed12/ZNEUS_ZS_Vach_Kmet_Duchon.git
                host: Kristof
                memory:
                    total: "25559359488"
                os: Windows-11-10.0.26100-SP0
                program: Project1.ipynb
                python: CPython 3.13.7
                root: C:\Data\VS\5.Semester\ZNEUS\projekt\ZNEUS_ZS_Vach_Kmet_Duchon
                startedAt: "2025-11-08T09:50:12.203798Z"
                writerId: agc3dc6u8ff91xiqoalef0q4lws08amr
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.7
            "5": 0.22.3
            "8":
                - 1
                - 3
            "12": 0.22.3
            "13": windows-amd64
clf__batch_size:
    value:
        - 256
        - 512
        - 1024
clf__lr:
    value:
        - 0.001
        - 0.005
        - 0.01
clf__max_epochs:
    value:
        - 15
        - 30
clf__module__dropout:
    value:
        - 0
        - 0.2
        - 0.5
clf__module__hidden:
    value:
        - - 256
          - 128
          - 64
        - - 128
          - 64
        - - 512
          - 256
          - 128
clf__optimizer:
    value:
        - torch.optim.adam.Adam
        - torch.optim.rmsprop.RMSprop
clf__y_tensor_transform:
    value:
        - __main__.y_tensor_transform
