_wandb:
    value:
        cli_version: 0.22.0
        e:
            2ixso15if6tidmkq6hf15230efzl5dgh:
                codePath: Project1.ipynb
                codePathLocal: Project1.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1022632464384"
                        used: "591241641984"
                email: xvachd@stuba.sk
                executable: C:\Users\david\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
                git:
                    commit: 01e07eae82ce156fe302e66e425d8b6551977480
                    remote: https://github.com/Daweed12/ZNEUS_ZS_Vach_Kmet_Duchon.git
                host: razdvach
                memory:
                    total: "33805824000"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\david\zneus\zneus_2025\ZNEUS_ZS_Vach_Kmet_Duchon\Project1.ipynb
                python: CPython 3.11.9
                root: c:\Users\david\zneus\zneus_2025\ZNEUS_ZS_Vach_Kmet_Duchon
                startedAt: "2025-11-10T17:06:41.279094Z"
                writerId: 2ixso15if6tidmkq6hf15230efzl5dgh
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 32
                - 53
            "2":
                - 1
                - 5
                - 32
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.11.9
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
batch_size:
    value: 1024
lr:
    value: 0.002
max_epochs:
    value: 60
module__dropout_rate:
    value: 0.3
module__hidden_layers:
    value:
        - 640
        - 320
        - 160
name:
    value: Test_5_F1_0.571
optimizer:
    value: torch.optim.adam.Adam
