_wandb:
    value:
        cli_version: 0.22.0
        e:
            qa9ikegijp3qs7nm667xyu55ce8bg50x:
                codePath: Project1.ipynb
                codePathLocal: Project1.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1022632464384"
                        used: "551503798272"
                email: xvachd@stuba.sk
                executable: C:\Users\david\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
                git:
                    commit: 0ae56aab7a3f8c76d09f740bdaf7dd8c0d79909a
                    remote: https://github.com/Daweed12/ZNEUS_ZS_Vach_Kmet_Duchon.git
                host: razdvach
                memory:
                    total: "33805824000"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\david\zneus\zneus_2025\ZNEUS_ZS_Vach_Kmet_Duchon\Project1.ipynb
                python: CPython 3.11.9
                root: c:\Users\david\zneus\zneus_2025\ZNEUS_ZS_Vach_Kmet_Duchon
                startedAt: "2025-11-08T17:20:24.100696Z"
                writerId: qa9ikegijp3qs7nm667xyu55ce8bg50x
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 32
                - 53
            "2":
                - 1
                - 5
                - 32
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.11.9
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
batch_size:
    value: 256
lr:
    value: 0.001
max_epochs:
    value: 150
module__dropout_rate:
    value: 0.6
module__hidden_layers:
    value:
        - 512
        - 256
        - 128
        - 64
name:
    value: Hlboky_model_vysoky_dropout
optimizer:
    value: torch.optim.adam.Adam
