_wandb:
    value:
        cli_version: 0.22.3
        e:
            5ngtaerax2uh0pbuf150sot22zxfi7t4:
                codePath: Project1.ipynb
                codePathLocal: Project1.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510567378944"
                        used: "424516685824"
                email: xkmetk@stuba.sk
                executable: C:\Users\krist\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: ca5ed1e2b02c28bde5ee8d683fd554784fabc01c
                    remote: https://github.com/Daweed12/ZNEUS_ZS_Vach_Kmet_Duchon.git
                host: Kristof
                memory:
                    total: "25559359488"
                os: Windows-11-10.0.26100-SP0
                program: Project1.ipynb
                python: CPython 3.13.7
                root: C:\Data\VS\5.Semester\ZNEUS\projekt\ZNEUS_ZS_Vach_Kmet_Duchon
                startedAt: "2025-11-08T12:45:35.882868Z"
                writerId: 5ngtaerax2uh0pbuf150sot22zxfi7t4
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "3":
                - 2
                - 13
            "4": 3.13.7
            "5": 0.22.3
            "8":
                - 1
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 512
dropout:
    value: 0.2
hidden_layers:
    value:
        - 256
        - 128
        - 64
lr:
    value: 0.005
max_epochs:
    value: 20
model_type:
    value: MLP
optimizer:
    value: Adam
