_wandb:
    value:
        cli_version: 0.22.3
        e:
            k7kqna1s2fj1s9s0lqjoim4fhcftp6a4:
                codePath: Project1.ipynb
                codePathLocal: Project1.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510567378944"
                        used: "427333169152"
                email: xkmetk@stuba.sk
                executable: C:\Users\krist\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 40c9a6af4282bc37b921b2f82568fa766e9a0994
                    remote: https://github.com/Daweed12/ZNEUS_ZS_Vach_Kmet_Duchon.git
                host: Kristof
                memory:
                    total: "25559359488"
                os: Windows-11-10.0.26100-SP0
                program: Project1.ipynb
                python: CPython 3.13.7
                root: C:\Data\VS\5.Semester\ZNEUS\projekt\ZNEUS_ZS_Vach_Kmet_Duchon
                startedAt: "2025-11-08T15:33:04.701924Z"
                writerId: k7kqna1s2fj1s9s0lqjoim4fhcftp6a4
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 32
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.13.7
            "5": 0.22.3
            "8":
                - 1
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 256
lr:
    value: 0.0005
max_epochs:
    value: 300
module__dropout_rate:
    value: 0.5
module__hidden_layers:
    value:
        - 1024
        - 512
        - 256
        - 128
        - 64
        - 32
name:
    value: exp_16_deep_6layers_adam_5e-4
optimizer:
    value: torch.optim.adam.Adam
